# Pose images (white background) -> transparent, cropped, embedded in poses.js
# Crop box is stored so every pose of a character is drawn at the same scale.
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
public static class PoseCut {
  public static string Make(string path, int targetH) {
    using (var src = new Bitmap(path)) {
      int w = (int)Math.Round(src.Width * (double)targetH / src.Height), h = targetH;
      using (var bmp = new Bitmap(w, h, PixelFormat.Format32bppArgb)) {
        using (var g = Graphics.FromImage(bmp)) {
          g.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
          g.DrawImage(src, 0, 0, w, h);
        }
        var data = bmp.LockBits(new Rectangle(0, 0, w, h), ImageLockMode.ReadWrite, bmp.PixelFormat);
        int stride = data.Stride;
        var px = new byte[stride * h];
        System.Runtime.InteropServices.Marshal.Copy(data.Scan0, px, 0, px.Length);
        var visited = new bool[w * h];
        var q = new Queue<int>();
        for (int x = 0; x < w; x++) { q.Enqueue(x); q.Enqueue((h - 1) * w + x); }
        for (int y = 0; y < h; y++) { q.Enqueue(y * w); q.Enqueue(y * w + w - 1); }
        while (q.Count > 0) {
          int i = q.Dequeue();
          if (visited[i]) continue;
          int x = i % w, y = i / w, o = y * stride + x * 4;
          int mn = Math.Min(px[o + 2], Math.Min(px[o + 1], px[o]));
          if (mn < 230) continue;
          visited[i] = true;
          int a = mn >= 245 ? 0 : (int)(255.0 * (245 - mn) / 15); if (a < 0) a = 0; if (a > 255) a = 255;
          px[o + 3] = (byte)a;
          if (x > 0) q.Enqueue(i - 1);
          if (x < w - 1) q.Enqueue(i + 1);
          if (y > 0) q.Enqueue(i - w);
          if (y < h - 1) q.Enqueue(i + w);
        }
        // enclosed background holes (e.g. between legs): large, almost pure white regions
        var comp = new List<int>();
        for (int s = 0; s < w * h; s++) {
          if (visited[s]) continue;
          int so = (s / w) * stride + (s % w) * 4;
          if (Math.Min(px[so + 2], Math.Min(px[so + 1], px[so])) < 246) continue;
          comp.Clear(); long sum = 0;
          var st = new Stack<int>(); st.Push(s); visited[s] = true;
          while (st.Count > 0) {
            int i = st.Pop(); comp.Add(i);
            int x = i % w, y = i / w, o = y * stride + x * 4;
            sum += Math.Min(px[o + 2], Math.Min(px[o + 1], px[o]));
            int[] nb = { x > 0 ? i - 1 : -1, x < w - 1 ? i + 1 : -1, y > 0 ? i - w : -1, y < h - 1 ? i + w : -1 };
            foreach (int n in nb) {
              if (n < 0 || visited[n]) continue;
              int no = (n / w) * stride + (n % w) * 4;
              if (Math.Min(px[no + 2], Math.Min(px[no + 1], px[no])) < 246) continue;
              visited[n] = true; st.Push(n);
            }
          }
          if (comp.Count >= 30 && sum / comp.Count >= 251)
            foreach (int i in comp) px[(i / w) * stride + (i % w) * 4 + 3] = 0;
        }
        System.Runtime.InteropServices.Marshal.Copy(px, 0, data.Scan0, px.Length);
        bmp.UnlockBits(data);
        int minX = w, minY = h, maxX = 0, maxY = 0;
        for (int y = 0; y < h; y++) for (int x = 0; x < w; x++)
          if (px[y * stride + x * 4 + 3] > 40) {
            if (x < minX) minX = x; if (x > maxX) maxX = x;
            if (y < minY) minY = y; if (y > maxY) maxY = y;
          }
        var r = new Rectangle(minX, minY, maxX - minX + 1, maxY - minY + 1);
        using (var cut = bmp.Clone(r, bmp.PixelFormat))
        using (var ms = new MemoryStream()) {
          cut.Save(ms, ImageFormat.Png);
          return "x:" + r.X + ",y:" + r.Y + ",w:" + r.Width + ",h:" + r.Height + ",fw:" + w + ",src:'data:image/png;base64," + Convert.ToBase64String(ms.ToArray()) + "'";
        }
      }
    }
  }
}
"@
$root = Split-Path $PSScriptRoot -Parent
$dir = Get-ChildItem $root -Directory | Where-Object { Test-Path (Join-Path $_.FullName 'RYUJI\idle.png') } | Select-Object -First 1
$names = 'AKARI','JACK','KAI','LUNA','MEILIN','NOIR','RYUJI','VIKTOR'
$poses = 'idle','crouch','kick','punch','hit'
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// auto-generated by tools/make_poses.ps1')
[void]$sb.AppendLine('window.POSES = {')
foreach ($n in $names) {
  [void]$sb.AppendLine("  ${n}: {")
  foreach ($p in $poses) {
    $f = Join-Path $dir.FullName "$n\$p.png"
    if (Test-Path $f) { [void]$sb.AppendLine("    ${p}: {" + [PoseCut]::Make($f, 280) + "},") }
  }
  [void]$sb.AppendLine('  },')
  Write-Output "$n done"
}
[void]$sb.AppendLine('};')
[System.IO.File]::WriteAllText((Join-Path $root 'poses.js'), $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
