// assets/*.webp を base64 で埋め込んだ assets.js を生成する: node tools/make_assets.js
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const names = ['zombie', 'boss', 'city'];
let out = '// auto-generated by tools/make_assets.js\nwindow.ASSETS = {\n';
for (const n of names) {
  const b64 = fs.readFileSync(path.join(root, 'assets', n + '.webp')).toString('base64');
  out += `  ${n}: 'data:image/webp;base64,${b64}',\n`;
}
out += '};\n';
fs.writeFileSync(path.join(root, 'assets.js'), out);
console.log('assets.js written', out.length);
