# 白背景のキャラ画像を透過・縮小し、sprites.js（base64埋め込み）を生成する
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
public static class SpriteCut {
  public static string Make(string path, int targetH) {
    using (var src = new Bitmap(path)) {
      int w = (int)Math.Round(src.Width * (double)targetH / src.Height), h = targetH;
      using (var bmp = new Bitmap(w, h, PixelFormat.Format32bppArgb)) {
        using (var g = Graphics.FromImage(bmp)) {
          g.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
          g.DrawImage(src, 0, 0, w, h);
        }
        var rect = new Rectangle(0, 0, w, h);
        var data = bmp.LockBits(rect, ImageLockMode.ReadWrite, bmp.PixelFormat);
        int stride = data.Stride;
        var px = new byte[stride * h];
        System.Runtime.InteropServices.Marshal.Copy(data.Scan0, px, 0, px.Length);
        // flood-fill near-white pixels from the border to make them transparent
        var visited = new bool[w * h];
        var q = new Queue<int>();
        for (int x = 0; x < w; x++) { q.Enqueue(x); q.Enqueue((h - 1) * w + x); }
        for (int y = 0; y < h; y++) { q.Enqueue(y * w); q.Enqueue(y * w + w - 1); }
        while (q.Count > 0) {
          int i = q.Dequeue();
          if (visited[i]) continue;
          int x = i % w, y = i / w, o = y * stride + x * 4;
          int mn = Math.Min(px[o + 2], Math.Min(px[o + 1], px[o]));
          if (mn < 222) continue;
          visited[i] = true;
          int a = (int)(255.0 * (255 - mn) / 33); if (a < 0) a = 0; if (a > 255) a = 255;
          px[o + 3] = (byte)a;
          if (x > 0) q.Enqueue(i - 1);
          if (x < w - 1) q.Enqueue(i + 1);
          if (y > 0) q.Enqueue(i - w);
          if (y < h - 1) q.Enqueue(i + w);
        }
        System.Runtime.InteropServices.Marshal.Copy(px, 0, data.Scan0, px.Length);
        bmp.UnlockBits(data);
        int minX = w, minY = h, maxX = 0, maxY = 0;
        for (int y = 0; y < h; y++) for (int x = 0; x < w; x++)
          if (px[y * stride + x * 4 + 3] > 40) {
            if (x < minX) minX = x; if (x > maxX) maxX = x;
            if (y < minY) minY = y; if (y > maxY) maxY = y;
          }
        using (var cut = bmp.Clone(new Rectangle(minX, minY, maxX - minX + 1, maxY - minY + 1), bmp.PixelFormat))
        using (var ms = new MemoryStream()) {
          cut.Save(ms, ImageFormat.Png);
          return Convert.ToBase64String(ms.ToArray());
        }
      }
    }
  }
}
"@
$root = Split-Path $PSScriptRoot -Parent
$names = 'AKARI','JACK','KAI','LUNA','MEILIN','NOIR','RYUJI','VIKTOR'
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// auto-generated by tools/make_sprites.ps1')
[void]$sb.AppendLine('window.SPRITES = {')
foreach ($n in $names) {
  $b64 = [SpriteCut]::Make((Join-Path $root "$n.png"), 400)
  [void]$sb.AppendLine("  ${n}: 'data:image/png;base64,$b64',")
  Write-Output "$n done"
}
[void]$sb.AppendLine('};')
[System.IO.File]::WriteAllText((Join-Path $root 'sprites.js'), $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
